# Generated by Django 3.2.5 on 2021-07-27 01:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20210726_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='Texto'),
            preserve_default=False,
        ),
    ]
