# Generated by Django 3.2.5 on 2021-08-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_person_hoja_vida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleados', verbose_name='Avatar'),
        ),
    ]
